/***
 *If this code runs it was created by Evgenii Sokol.
 *If it doesn't work, I don't know who was created it.
 ***/

package com.turbosokol.TimeTask.repository.datasource

import com.turbosokol.TimeTask.database.TaskDatabase
import com.turbosokol.TimeTask.repository.data.TaskDto
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
// Using basic SQLDelight without coroutines extensions

/**
 * JVM-specific SQLDelight implementation of LocalTaskDataSource
 */
class SqlDelightLocalTaskDataSource(
    private val database: TaskDatabase
) : LocalTaskDataSource {

    override suspend fun getAllTasks(): List<TaskDto> {
        println("SqlDelightLocalTaskDataSource: getAllTasks called")
        val tasks = database.taskDatabaseQueries.selectAll().executeAsList().map { task ->
            TaskDto(
                id = task.id.toInt(),
                title = task.title,
                description = task.description,
                isActive = task.is_active == 1L,
                timeSeconds = task.time_seconds,
                timeHours = task.time_hours,
                color = task.color
            )
        }
        println("SqlDelightLocalTaskDataSource: Retrieved ${tasks.size} tasks from database")
        tasks.forEach { task ->
            println("  - Task ID: ${task.id}, Title: '${task.title}'")
        }
        return tasks
    }

    override suspend fun getTaskById(id: Int): TaskDto? {
        return database.taskDatabaseQueries.selectById(id.toLong()).executeAsOneOrNull()?.let { task ->
            TaskDto(
                id = task.id.toInt(),
                title = task.title,
                description = task.description,
                isActive = task.is_active == 1L,
                timeSeconds = task.time_seconds,
                timeHours = task.time_hours,
                color = task.color
            )
        }
    }

    override suspend fun upsertTask(task: TaskDto) {
        println("SqlDelightLocalTaskDataSource: upsertTask called - ID: ${task.id}, title: '${task.title}'")
        
        if (task.id == 0) {
            println("SqlDelightLocalTaskDataSource: Inserting new task (ID = 0)")
            // Insert new task - ID will be auto-generated by SQLite AUTOINCREMENT
            database.taskDatabaseQueries.insertTask(
                title = task.title,
                description = task.description,
                is_active = if (task.isActive) 1L else 0L,
                time_seconds = task.timeSeconds,
                time_hours = task.timeHours,
                color = task.color
            )
            println("SqlDelightLocalTaskDataSource: New task inserted successfully")
        } else {
            println("SqlDelightLocalTaskDataSource: Updating existing task (ID = ${task.id})")
            // Update existing task - use provided ID
            database.taskDatabaseQueries.updateTask(
                title = task.title,
                description = task.description,
                is_active = if (task.isActive) 1L else 0L,
                time_seconds = task.timeSeconds,
                time_hours = task.timeHours,
                color = task.color,
                id = task.id.toLong()
            )
            println("SqlDelightLocalTaskDataSource: Existing task updated successfully")
        }
    }

    override suspend fun upsertTasks(tasks: List<TaskDto>) {
        tasks.forEach { task ->
            upsertTask(task)
        }
    }

    override suspend fun deleteTask(id: Int) {
        database.taskDatabaseQueries.deleteTaskById(id.toLong())
    }

    override suspend fun deleteAllTasks() {
        database.taskDatabaseQueries.deleteAllTasks()
    }
}